#include <hal.h>

void uart_init(void)
{
    unsigned long baud = 9600;
    unsigned long spbrg;

    TXSTAbits.SYNC = 0;
    TXSTAbits.BRGH = 1;
    BAUDCONbits.BRG16 = 1;

    spbrg = (_XTAL_FREQ / (4UL * baud)) - 1;

    SPBRG = spbrg & 0xFF;
    SPBRGH = (spbrg >> 8) & 0xFF;

    RCSTAbits.SPEN = 1;
    TXSTAbits.TXEN = 1;
    RCSTAbits.CREN = 1;
}

#pragma interrupt_level 1
#pragma interrupt_level 2
inline void uart_putchar(char c)
{
    while (!TXSTAbits.TRMT)
        ;
    TXREG = c;
}

inline char uart_getchar(void)
{
    while (!PIR1bits.RCIF)
        ;
    return RCREG;
}

void extern_memory_init(void)
{
    /**
     * RA2 and RA3 are the inputs of the decoder
     * The gray code is used here to ensure two ajacent states are different
     * only by one bit.
     *
     * The order of states are defined as follows:
     * -------------------------
     * | RA3 | RA2 |  meaning  |
     * -------------------------
     * |  1  |  0  |  latch 1  |
     * |  0  |  0  |  latch 0  |
     * |  0  |  1  |     x     |
     * |  1  |  1  | start R/W |
     * -------------------------
     */
    asm("BCF TRISA, 0\n"
        "BCF TRISA, 1\n"
        "BCF TRISA, 2\n"
        "BCF TRISA, 3\n"
        "BSF LATA, 0\n"
        "BSF LATA, 1\n"
        "BCF LATA, 2\n"
        "BSF LATA, 3\n"
        "CLRF TRISB\n");
}

void extern_memory_write(uint16_t block_addr, char *src)
{
    FSR0L = ((uint16_t) src) & 0xFF;
    FSR0H = (((uint16_t) src) >> 8) & 0xFF;

    LATB = block_addr >> 8;
    asm("BCF LATA, 3\n"
        "NOP\n");
    LATB = block_addr & 0xFF;
    asm("BSF LATA, 2\n"
        "NOP\n"
        "BCF LATA, 0\n"
        "BSF LATA, 3\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "MOVFF POSTINC0, LATB\n"
        "BSF LATA, 0\n"
        "BCF LATA, 2\n");
}

void extern_memory_read(uint16_t block_addr, char *dest)
{
    FSR0L = ((uint16_t) dest) & 0xFF;
    FSR0H = (((uint16_t) dest) >> 8) & 0xFF;

    LATB = block_addr >> 8;
    asm("BCF LATA, 3\n"
        "NOP\n");

    LATB = block_addr & 0xFF;
    asm("BSF LATA, 2\n"
        "NOP\n"
        "BCF LATA, 1\n"
        "BSF LATA, 3\n"
        "SETF TRISB\n"
        "NOP\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "MOVFF PORTB, POSTINC0\n"
        "BSF LATA, 1\n"
        "BCF LATA, 2\n"
        "CLRF TRISB\n");
}
